
index_img: /img/homepage.jpg
katex:
  enable: true
  per_page: true
  hide_scrollbar: true

inject:
  head:
    - <link rel="stylesheet" href="/css/style.css">

beautify:
  enable: true
  field: post # site/post
  title-prefix-icon: '\f52d' # '\f0c1'
  title-prefix-icon-color: '#F47466'  # '#F47466'

comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use: 
    - Utterances
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: false
  count: false # Display comment count in post's top_img
  card_post_count: false # Display comment count in Home Page


utterances:
  enable: true
  repo: andrewli315/andrewli315.github.io
  issue_term: pathname
  light_theme: github-light
  dark_theme: photon-dark
  label: utterances